---
- name: Trigger Playbooks
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Run Playbook_Network_Interface.yml
      include_playbook: Playbook_Network_Interface.yml

    - name: Run Playbook_Install_Server.yml
      include_playbook: Playbook_Install_Server.yml

    - name: Run Playbook_Install_Client.yml
      include_playbook: Playbook_Install_Client.yml