---
- name: Play for setting up WireGuard client from peer.conf

  hosts: wireguard_clients

  tasks:
    - name: Read peer.conf file from Ansible controller
      ansible.builtin.command: cat peer.conf
      delegate_to: localhost
      register: peer_conf_content
      changed_when: false

    - name: Display peer.conf content (for debugging)
      ansible.builtin.debug:
        msg: "{{ peer_conf_content.stdout }}"

    - name: Install WireGuard
      become: true
      become_user: root
      ansible.builtin.apt:
        name: wireguard
        state: present
        update_cache: true

    - name: Create WireGuard configuration for the client
      become: true
      become_user: root
      ansible.builtin.copy:
        content: "{{ peer_conf_content.stdout }}"
        dest: /etc/wireguard/wg0.conf
        mode: "0600"
        force: true

    - name: Enable and start WireGuard service
      become: true
      become_user: root
      ansible.builtin.systemd:
        name: wg-quick@wg0
        state: started
        enabled: true
