---
- name: Trigger Playbooks
  hosts: localhost
  gather_facts: false

  tasks:


    - name: Run Playbook_Install_Server.yml
      include_playbook: Playbook_Install_Server.yml

    - name: Run Playbook_Install_Client.yml
      include_playbook: Playbook_Install_Client.yml

    - name: Run test.yml
      include_playbook: Roles/wireguard_server/tests/test.yml