---
- name: Play for setting up WireGuard client from peer.conf

  hosts: wireguard_client

  tasks:
    - name: Read peer configusration file from Ansible controller
      ansible.builtin.command: cat peer.conf
      delegate_to: localhost
      register: peer_conf_content
      changed_when: false

    - name: Display peer.conf content (for debugging)
      ansible.builtin.debug:
        msg: "{{ peer_conf_content.stdout }}"

    - name: Install WireGuard
      become: true
      become_user: root
      ansible.builtin.apt:
        name: wireguard
        state: present
        update_cache: true

    - name: Create WireGuard configuration for the client
      become: true
      become_user: root
      ansible.builtin.copy:
        content: "{{ peer_conf_content.stdout }}"
        dest: /etc/wireguard/wg0.conf
        mode: "0600"
        force: true
   
    - name: Read client_private_key file
      ansible.builtin.command: cat client_private_key
      delegate_to: localhost
      register: private_key_content
      changed_when: false

    
    - name: Copy client private key to privatekey
      become: true
      become_user: root
      ansible.builtin.copy:
         content: "{{ private_key_content.stdout }}"
         dest: /etc/wireguard/privatekey
         mode: "0600"
         force: true 


    - name: Read client_public_key file
      ansible.builtin.command: cat client_public_key
      delegate_to: localhost
      register: public_key_content
      changed_when: false

    
    - name: Copy client public key to /etc/wireguard/publickey
      become: true
      become_user: root
      ansible.builtin.copy:
         content: "{{ public_key_content.stdout }}"
         dest: /etc/wireguard/publickey
         mode: "0600"
         force: true 

    - name: Enable IPv4 forwarding in sysctl.conf
      become: true
      become_user: root
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        line: "net.ipv4.ip_forward = 1"
        state: present
      notify: Reboot

    - name: Apply sysctl settings
      become: true
      become_user: root
      ansible.builtin.command: "sysctl -p"
      register: output
      changed_when: output.rc != 0

    - name: Enable WireGuard service
      become: true
      become_user: root
      ansible.builtin.systemd:
        name: wg-quick@wg0
        enabled: yes
        state: started
      notify: Reboot  
   


